parameters:
#    domain: http://indianautosblogv2.local
#    mobile: http://m.indianautosblogv2.local
#    site_name: Indian Autos blog
#    home_title: Global Auto News, Rumours, Scoops, Spyshots and Renders with emphasis on the Indian Auto Market.
#    site_desc: Global Auto News, Rumours, Scoops, Spyshots and Renders with emphasis on the Indian Auto Market.
#    site_key:
#    site_logo: https://img.indianautosblog.com/2017/07/Logo.png
#
## Common config
#    static_url:
#    media_url: https://img.indianautosblog.com
#    media_version: 1.0.0
#    preview_key: aWFiIHByZXZpZXcgc2FsdA==
#    elasticsearch_url: http://172.16.0.116:9200/
## Cache config
#    cache_time:
#        hour: 3600
#        short: 21600
#        medium: 86400
#        long: 604800
#Redis
    cache_config:
        refresh_cache: 123456
        manual_cache: 123456
        allow_cache_data: 0
        allow_cache_page: 0
        redisArticle: 172.16.0.13:6377:8:2.5
        redisCachePage: 172.16.0.13:6377:5:2.5
        redisUpdateView: 172.16.0.13:6377:15